# Generated by Django 3.2.2 on 2021-07-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient')], default='doctor', max_length=255),
        ),
    ]
